### ISSUE TITLE
[Bug] Calculateur de Moyennes affiche 'NaN'

### ISSUE THREAD

**Issue by leo539** [Bastian-Noel/Nouvelle-Interface-pour-EcoleDirecte#2]
Bonjour, d'abord j'apprécie beaucoup votre travail, c'est un projet superbe et j'ai hate de voir des nouvelles MAJ. Mais, j'ai un souci avec la calculatrice de moyennes. Quand je cliques sur le bouton "Calculateur de moyenne", la première note de tous les matières avec plus de 2 notes apparait comme NaN. Donc, la moyenne affiché est NaN. Je n'y connait pas trop en programation et j'ai regardé un peu dans la console developpeur mais je ne trouve rien qui pourrait faire cela. Merci

**Comment by leo539** [comment]
<img width="374" alt="Screenshot 2022-12-07 at 19 30 28" src="https://user-images.githubusercontent.com/65543927/206265989-0434d86e-f5a6-479e-83cf-1c32212df470.png">
Voici^^
Les pages "Moyennes" et "Graphiques" ne marchent pas nonplus mais je suppose que ce sont des données qui viennent de Ecole Directe donc vous n'y pouvez rien?

**Comment by Bastian-Noel** [comment]
Des problèmes de ce type ont déjà été signalés, et la source du bug a peut être été trouver. Je manque malheureusement de temps en ce moment pour le corriger, je pense pouvoir régler cela d’ici 1 semaine.

**Comment by leo539** [comment]
Merci Beaucoup Bastien

**Comment by Bastian-Noel** [comment]
Mettre a jours vers la v5.0.2
